export const CREATE_CONTACT = "CREATE_CONTACT";
export const RETRIEVE_CONTACTS = "RETRIEVE_CONTACTS";
export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const DELETE_ALL_CONTACTS = "DELETE_ALL_CONTACTS";